# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ dev, test, pre, gray, sim, prod, master, main ]
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Test it On ${{matrix.os}} and ${{matrix.go-version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go-version: [ 1.16, 1.17, 1.18, 1.19 ]
        os: [
          ubuntu-18.04,
          ubuntu-20.04,
          ubuntu-latest,
          macos-10.15,
          macos-11,
          macos-latest,
        ]
    steps:
      - uses: actions/checkout@v3

      - name: Use go ${{ matrix.go-version }} environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -v ./...